import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter_logging_service/flutter_logging_service.dart';

import '../../../core/layout/layout_breakpoints.dart';
import '../../../core/layout/responsive_sheet.dart';
import '../../../core/repository/repository_providers.dart';
import '../../../core/utils/currency_formatter.dart';
import '../../../core/widgets/toast.dart';
import '../../../domain/domain.dart';

/// Show a confirmation bottom sheet to record a settlement payment.
/// Returns `true` if the settlement was recorded, `false` if cancelled.
Future<bool> showRecordSettlementSheet(
  BuildContext context,
  WidgetRef ref, {
  required String groupId,
  required String currencyCode,
  required SettlementTransaction settlement,
  required String fromName,
  required String toName,
}) async {
  final result = await showResponsiveSheet<bool>(
    context: context,
    title: 'record_settlement'.tr(),
    useSafeArea: true,
    centerInFullViewport: true,
    child: _RecordSettlementSheet(
      groupId: groupId,
      currencyCode: currencyCode,
      settlement: settlement,
      fromName: fromName,
      toName: toName,
    ),
  );
  if (result == true) {
    // Create the transfer expense
    try {
      final expense = Expense(
        id: '', // will be generated by repository
        groupId: groupId,
        payerParticipantId: settlement.fromParticipantId,
        amountCents: settlement.amountCents,
        currencyCode: currencyCode,
        title: 'settlement_expense_title'.tr(namedArgs: {'from': fromName, 'to': toName}),
        date: DateTime.now(),
        splitType: SplitType.amounts,
        splitShares: {settlement.toParticipantId: settlement.amountCents},
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        transactionType: TransactionType.transfer,
        toParticipantId: settlement.toParticipantId,
      );
      await ref.read(expenseRepositoryProvider).create(expense);
      Log.info(
        'Settlement recorded: $fromName -> $toName for ${settlement.amountCents} cents',
      );
      return true;
    } catch (e, st) {
      Log.error('Failed to record settlement', error: e, stackTrace: st);
      if (context.mounted) {
        context.showError('record_settlement_failed'.tr());
      }
      return false;
    }
  }
  return false;
}

class _RecordSettlementSheet extends StatelessWidget {
  final String groupId;
  final String currencyCode;
  final SettlementTransaction settlement;
  final String fromName;
  final String toName;

  const _RecordSettlementSheet({
    required this.groupId,
    required this.currencyCode,
    required this.settlement,
    required this.fromName,
    required this.toName,
  });

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final formattedAmount = CurrencyFormatter.formatCents(
      settlement.amountCents,
      currencyCode,
    );

    return Padding(
      padding: EdgeInsets.fromLTRB(
        24,
        24,
        24,
        24 + MediaQuery.of(context).padding.bottom,
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(
            Icons.payments_outlined,
            size: 48,
            color: theme.colorScheme.primary,
          ),
          const SizedBox(height: 16),
          if (!LayoutBreakpoints.isTabletOrWider(context)) ...[
            Text('record_settlement'.tr(), style: theme.textTheme.titleLarge),
            const SizedBox(height: 12),
          ],
          Text(
            'record_settlement_confirm'.tr(
              namedArgs: {
                'from': fromName,
                'to': toName,
                'amount': formattedAmount,
              },
            ),
            textAlign: TextAlign.center,
            style: theme.textTheme.bodyLarge,
          ),
          const SizedBox(height: 24),
          Row(
            mainAxisAlignment: MainAxisAlignment.end,
            children: [
              if (!LayoutBreakpoints.isTabletOrWider(context))
                TextButton(
                  onPressed: () => Navigator.of(context).pop(false),
                  child: Text('cancel'.tr()),
                ),
              if (!LayoutBreakpoints.isTabletOrWider(context)) const SizedBox(width: 12),
              FilledButton.icon(
                onPressed: () => Navigator.of(context).pop(true),
                icon: const Icon(Icons.check),
                label: Text('record_settlement'.tr()),
              ),
            ],
          ),
        ],
      ),
    );
  }
}
