import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter_logging_service/flutter_logging_service.dart';

import '../../../core/layout/layout_breakpoints.dart';
import '../../../core/layout/responsive_sheet.dart';
import '../../../core/repository/repository_providers.dart';
import '../../../core/services/settle_up_service.dart';
import '../../../core/theme/accent_style.dart';
import '../../../core/utils/currency_formatter.dart';
import '../../../core/utils/user_text.dart';
import '../../../core/widgets/participant_avatar.dart';
import '../../../core/widgets/toast.dart';
import '../../../core/widgets/user_text.dart';
import '../../../domain/domain.dart';
import '../providers/balance_provider.dart';
import '../../groups/providers/groups_provider.dart';

/// Show a confirmation bottom sheet to record a settlement payment.
/// Returns `true` if the settlement was recorded, `false` if cancelled.
Future<bool> showRecordSettlementSheet(
  BuildContext context,
  WidgetRef ref, {
  required String groupId,
  required String currencyCode,
  required SettlementTransaction settlement,
  required String fromName,
  required String toName,
  String? fromAvatarId,
  String? toAvatarId,
}) async {
  final result = await showResponsiveSheet<bool>(
    context: context,
    title: 'record_settlement'.tr(),
    useSafeArea: true,
    centerInFullViewport: true,
    child: _RecordSettlementSheet(
      groupId: groupId,
      currencyCode: currencyCode,
      settlement: settlement,
      fromName: fromName,
      toName: toName,
      fromAvatarId: fromAvatarId,
      toAvatarId: toAvatarId,
    ),
  );
  if (result == true) {
    // Create the transfer expense
    try {
      final group = await ref.read(groupRepositoryProvider).getById(groupId);
      if (group == null) return false;
      if (group.isArchived) {
        if (context.mounted) {
          context.showToast('record_settlement_blocked_archived'.tr());
        }
        return false;
      }
      if (group.isSettlementFrozen) {
        if (context.mounted) {
          context.showToast('settlement_frozen_hint'.tr());
        }
        return false;
      }
      final expense = Expense(
        id: '', // will be generated by repository
        groupId: groupId,
        payerParticipantId: settlement.fromParticipantId,
        amountCents: settlement.amountCents,
        currencyCode: currencyCode,
        // Do not wrap names in bidi isolates here — this title is persisted.
        title: 'settlement_expense_title'.tr(
          namedArgs: {'from': fromName, 'to': toName},
        ),
        date: DateTime.now(),
        splitType: SplitType.amounts,
        splitShares: {settlement.toParticipantId: settlement.amountCents},
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        transactionType: TransactionType.transfer,
        toParticipantId: settlement.toParticipantId,
      );
      await ref.read(expenseRepositoryProvider).create(expense);
      // Force an immediate refresh so the Balance tab reflects the new transfer
      // even when repository stream updates arrive slightly later.
      ref.invalidate(expensesByGroupProvider(groupId));
      ref.invalidate(groupBalanceProvider(groupId));
      Log.info(
        'Settlement recorded: $fromName -> $toName for ${settlement.amountCents} cents',
      );
      return true;
    } catch (e, st) {
      Log.error('Failed to record settlement', error: e, stackTrace: st);
      if (context.mounted) {
        context.showError('record_settlement_failed'.tr());
      }
      return false;
    }
  }
  return false;
}

class _RecordSettlementSheet extends ConsumerWidget {
  final String groupId;
  final String currencyCode;
  final SettlementTransaction settlement;
  final String fromName;
  final String toName;
  final String? fromAvatarId;
  final String? toAvatarId;

  const _RecordSettlementSheet({
    required this.groupId,
    required this.currencyCode,
    required this.settlement,
    required this.fromName,
    required this.toName,
    this.fromAvatarId,
    this.toAvatarId,
  });

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final theme = Theme.of(context);
    final cs = theme.colorScheme;
    final formattedAmount = CurrencyFormatter.formatCents(
      settlement.amountCents,
      currencyCode,
    );
    final expensesAsync = ref.watch(expensesByGroupProvider(groupId));
    final expenses = expensesAsync.asData?.value ?? const <Expense>[];
    final breakdown = computePairExpenseBreakdown(
      fromParticipantId: settlement.fromParticipantId,
      toParticipantId: settlement.toParticipantId,
      expenses: expenses,
    );
    // Consolidated settlements already carry one-direction items — don't mix in
    // the reverse leg (that method does not net pairwise).
    final hasAlgorithmItems =
        settlement.items != null && settlement.items!.isNotEmpty;
    final fromOwesItems = hasAlgorithmItems
        ? settlement.items!
        : breakdown.owedByFromToTo;
    final toOwesItems = hasAlgorithmItems
        ? const <SettlementItem>[]
        : breakdown.owedByToToFrom;
    final fromOwesTotal = fromOwesItems.fold<int>(
      0,
      (s, i) => s + i.amountCents,
    );
    final toOwesTotal = toOwesItems.fold<int>(0, (s, i) => s + i.amountCents);
    final pairNet = fromOwesTotal - toOwesTotal;
    final explainsTransfer = fromOwesItems.isNotEmpty || toOwesItems.isNotEmpty;
    final isOptimized =
        explainsTransfer && pairNet != settlement.amountCents;

    return Padding(
      padding: EdgeInsets.fromLTRB(
        16,
        16,
        16,
        16 + MediaQuery.paddingOf(context).bottom,
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          if (!LayoutBreakpoints.isTabletOrWider(context)) ...[
            Text(
              'record_settlement'.tr(),
              style: theme.textTheme.titleMedium?.copyWith(
                fontWeight: FontWeight.w700,
              ),
            ),
            const SizedBox(height: 12),
          ],
          DecoratedBox(
            decoration: AccentSurfaces.panel(
              cs,
              subtle: context.subtleAccents,
            ),
            child: Padding(
              padding: const EdgeInsets.all(16),
              child: Column(
                children: [
                  Row(
                    children: [
                      Expanded(
                        child: _SheetPerson(
                          name: fromName,
                          avatarId: fromAvatarId,
                        ),
                      ),
                      Padding(
                        padding: const EdgeInsets.symmetric(horizontal: 8),
                        child: Text(
                          '\u200E\u2192\u200E',
                          style: theme.textTheme.titleMedium?.copyWith(
                            color: cs.primary,
                            fontWeight: FontWeight.w700,
                          ),
                        ),
                      ),
                      Expanded(
                        child: _SheetPerson(
                          name: toName,
                          avatarId: toAvatarId,
                          alignEnd: true,
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 14),
                  Text(
                    formattedAmount,
                    style: theme.textTheme.headlineSmall?.copyWith(
                      fontWeight: FontWeight.w800,
                    ),
                  ),
                  const SizedBox(height: 6),
                  UserText(
                    'record_settlement_confirm'.tr(
                      namedArgs: {
                        'from': isolateBidi(fromName),
                        'to': isolateBidi(toName),
                        'amount': formattedAmount,
                      },
                    ),
                    textAlign: TextAlign.center,
                    style: theme.textTheme.bodyMedium?.copyWith(
                      color: cs.onSurfaceVariant,
                    ),
                  ),
                ],
              ),
            ),
          ),
          const SizedBox(height: 14),
          Align(
            alignment: AlignmentDirectional.centerStart,
            child: Text(
              'settlement_breakdown_title'.tr(),
              style: theme.textTheme.titleSmall?.copyWith(
                fontWeight: FontWeight.w700,
              ),
            ),
          ),
          const SizedBox(height: 8),
          DecoratedBox(
            decoration: AccentSurfaces.flatPanel(cs),
            child: ConstrainedBox(
              constraints: BoxConstraints(
                maxHeight: MediaQuery.sizeOf(context).height * 0.35,
              ),
              child: SingleChildScrollView(
                padding: const EdgeInsets.fromLTRB(12, 10, 12, 10),
                child: !explainsTransfer
                    ? Column(
                        crossAxisAlignment: CrossAxisAlignment.stretch,
                        children: [
                          Text(
                            'settlement_no_shared_expenses'.tr(),
                            style: theme.textTheme.bodySmall?.copyWith(
                              color: cs.onSurfaceVariant,
                            ),
                          ),
                          const SizedBox(height: 8),
                          Text(
                            'settlement_optimized_hint'.tr(),
                            style: theme.textTheme.bodySmall?.copyWith(
                              color: cs.onSurfaceVariant,
                            ),
                          ),
                        ],
                      )
                    : Column(
                        crossAxisAlignment: CrossAxisAlignment.stretch,
                        children: [
                          if (fromOwesItems.isNotEmpty) ...[
                            _BreakdownSectionHeader(
                              label: 'settlement_paid_by'.tr(
                                namedArgs: {'name': isolateBidi(toName)},
                              ),
                            ),
                            ...fromOwesItems.map(
                              (item) => _BreakdownLine(
                                title: item.title,
                                amountCents: item.amountCents,
                                currencyCode: currencyCode,
                                signedPositive: true,
                              ),
                            ),
                          ],
                          if (toOwesItems.isNotEmpty) ...[
                            if (fromOwesItems.isNotEmpty)
                              const SizedBox(height: 8),
                            _BreakdownSectionHeader(
                              label: 'settlement_paid_by'.tr(
                                namedArgs: {'name': isolateBidi(fromName)},
                              ),
                            ),
                            ...toOwesItems.map(
                              (item) => _BreakdownLine(
                                title: item.title,
                                amountCents: item.amountCents,
                                currencyCode: currencyCode,
                                // Offsetting side — shown as reducing what from owes.
                                signedPositive: false,
                              ),
                            ),
                          ],
                          if (fromOwesItems.isNotEmpty &&
                              toOwesItems.isNotEmpty) ...[
                            const SizedBox(height: 8),
                            Divider(
                              height: 1,
                              color: cs.outlineVariant.withValues(alpha: 0.45),
                            ),
                            const SizedBox(height: 8),
                            Row(
                              children: [
                                Expanded(
                                  child: Text(
                                    'settlement_net'.tr(),
                                    style: theme.textTheme.labelLarge?.copyWith(
                                      fontWeight: FontWeight.w700,
                                    ),
                                  ),
                                ),
                                Text(
                                  CurrencyFormatter.formatCents(
                                    settlement.amountCents,
                                    currencyCode,
                                  ),
                                  style: theme.textTheme.labelLarge?.copyWith(
                                    fontWeight: FontWeight.w800,
                                  ),
                                ),
                              ],
                            ),
                          ],
                          if (isOptimized) ...[
                            const SizedBox(height: 8),
                            Text(
                              'settlement_optimized_hint'.tr(),
                              style: theme.textTheme.bodySmall?.copyWith(
                                color: cs.onSurfaceVariant,
                              ),
                            ),
                          ],
                        ],
                      ),
              ),
            ),
          ),
          const SizedBox(height: 16),
          Row(
            mainAxisAlignment: MainAxisAlignment.end,
            children: [
              if (!LayoutBreakpoints.isTabletOrWider(context))
                TextButton(
                  onPressed: () => Navigator.of(context).pop(false),
                  child: Text('cancel'.tr()),
                ),
              if (!LayoutBreakpoints.isTabletOrWider(context))
                const SizedBox(width: 12),
              FilledButton.icon(
                onPressed: () => Navigator.of(context).pop(true),
                icon: const Icon(Icons.check),
                label: Text('record_settlement'.tr()),
              ),
            ],
          ),
        ],
      ),
    );
  }
}

class _SheetPerson extends StatelessWidget {
  final String name;
  final String? avatarId;
  final bool alignEnd;

  const _SheetPerson({
    required this.name,
    this.avatarId,
    this.alignEnd = false,
  });

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final cs = theme.colorScheme;
    final avatar = ParticipantAvatar(
      name: name,
      avatarId: avatarId,
      radius: 16,
      backgroundColor: cs.primary.withValues(alpha: 0.12),
      foregroundColor: cs.primary,
      textStyle: theme.textTheme.labelMedium,
    );
    final label = UserText(
      name,
      maxLines: 2,
      overflow: TextOverflow.ellipsis,
      textAlign: alignEnd ? TextAlign.end : TextAlign.start,
      style: theme.textTheme.bodyMedium?.copyWith(fontWeight: FontWeight.w600),
    );
    return alignEnd
        ? Row(
            mainAxisAlignment: MainAxisAlignment.end,
            children: [
              Flexible(child: label),
              const SizedBox(width: 8),
              avatar,
            ],
          )
        : Row(
            children: [
              avatar,
              const SizedBox(width: 8),
              Flexible(child: label),
            ],
          );
  }
}

class _BreakdownSectionHeader extends StatelessWidget {
  final String label;

  const _BreakdownSectionHeader({required this.label});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Padding(
      padding: const EdgeInsets.only(bottom: 4),
      child: UserText(
        label,
        style: theme.textTheme.labelMedium?.copyWith(
          color: theme.colorScheme.onSurfaceVariant,
          fontWeight: FontWeight.w700,
        ),
      ),
    );
  }
}

class _BreakdownLine extends StatelessWidget {
  final String title;
  final int amountCents;
  final String currencyCode;
  final bool signedPositive;

  const _BreakdownLine({
    required this.title,
    required this.amountCents,
    required this.currencyCode,
    required this.signedPositive,
  });

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final cs = theme.colorScheme;
    final amount = CurrencyFormatter.formatCents(amountCents, currencyCode);
    final prefix = signedPositive ? '+' : '−';
    return Padding(
      padding: const EdgeInsets.only(bottom: 4),
      child: Row(
        children: [
          Expanded(
            child: UserText(
              title,
              maxLines: 1,
              overflow: TextOverflow.ellipsis,
              style: theme.textTheme.bodyMedium,
            ),
          ),
          const SizedBox(width: 8),
          Text(
            '$prefix$amount',
            style: theme.textTheme.bodyMedium?.copyWith(
              fontWeight: FontWeight.w600,
              color: signedPositive ? cs.onSurface : cs.onSurfaceVariant,
            ),
          ),
        ],
      ),
    );
  }
}
