import 'dart:ui' as ui;

import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';

/// The parallax layers were exported with a magenta chroma key. Two defects
/// came out of that and both showed up on screen as a purple, speckled rim
/// around every silhouette:
///
/// * edge pixels held premultiplied colour in a straight-alpha PNG, so Flutter
///   premultiplied a second time on decode and darkened the rim;
/// * some edge pixels kept the key colour itself.
///
/// These assets are regenerated by hand, so guard both properties.
void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  const layers = [
    'hills_far',
    'hills_mid',
    'grass',
    'grass_front',
  ];

  Future<(int, int, ByteData)> loadRgba(String name) async {
    final bytes = await rootBundle.load('assets/images/parallax/$name.png');
    final codec = await ui.instantiateImageCodec(
      bytes.buffer.asUint8List(),
    );
    final frame = await codec.getNextFrame();
    final data = await frame.image.toByteData(
      format: ui.ImageByteFormat.rawRgba,
    );
    return (frame.image.width, frame.image.height, data!);
  }

  for (final variant in ['', '_night']) {
    for (final layer in layers) {
      final name = '$layer$variant';

      test('$name has no chroma key left on its edges', () async {
        final (width, height, data) = await loadRgba(name);
        var keyed = 0;
        for (var i = 0; i < width * height; i++) {
          final o = i * 4;
          final a = data.getUint8(o + 3);
          if (a == 0 || a == 255) continue;
          final r = data.getUint8(o);
          final g = data.getUint8(o + 1);
          final b = data.getUint8(o + 2);
          // Magenta is red and blue without green, so any edge pixel where
          // both outrank green is left-over key colour.
          if (r > g + 6 && b > g + 6) keyed++;
        }
        expect(keyed, 0, reason: '$name has $keyed magenta edge pixels');
      });

      test('$name stores straight alpha, not premultiplied', () async {
        final (width, height, data) = await loadRgba(name);
        // Premultiplied edges darken in lockstep with alpha, so an edge pixel
        // ends up far dimmer than the opaque artwork it borders. Compare each
        // edge pixel against the brightest fully opaque pixel in its column.
        var darkened = 0;
        var sampled = 0;
        for (var x = 0; x < width; x += 7) {
          var opaqueLuma = 0;
          for (var y = 0; y < height; y++) {
            final o = (y * width + x) * 4;
            if (data.getUint8(o + 3) != 255) continue;
            final luma = (data.getUint8(o) * 2 +
                    data.getUint8(o + 1) * 5 +
                    data.getUint8(o + 2)) ~/
                8;
            if (luma > opaqueLuma) opaqueLuma = luma;
          }
          if (opaqueLuma == 0) continue;
          for (var y = 0; y < height; y++) {
            final o = (y * width + x) * 4;
            final a = data.getUint8(o + 3);
            if (a < 128 || a == 255) continue;
            sampled++;
            final luma = (data.getUint8(o) * 2 +
                    data.getUint8(o + 1) * 5 +
                    data.getUint8(o + 2)) ~/
                8;
            if (luma < opaqueLuma ~/ 4) darkened++;
          }
        }
        expect(sampled, greaterThan(0), reason: '$name has no edge pixels');
        expect(
          darkened / sampled,
          // Repaired assets sit near 1.5% (genuinely shadowed edges); the
          // premultiplied exports were above 6%.
          lessThan(0.03),
          reason: '$name looks premultiplied: $darkened of $sampled edge '
              'pixels are far darker than their column artwork',
        );
      });
    }
  }
}
